spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.60:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.3.60
    port: 6379

server:
  context-path: /sell

wechat:
  mpAppId: wx00d5772bc0058d9b
  mpAppSecret: 5d13ed8ff75b1288905c800e9f698e57
  mchId: 1501682081
  mchKey: 4ecdb062b1c34de3afd2a8d096ee2845
  keyPath: E:/ideaWorkspaces/dev/java/imooc/sell/src/main/resources/static/cert/apiclient_cert.p12
  notifyUrl: http://7dian.nat300.top/sell/pay/notify
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  templateId:
    orderStatus: _eWrenS5n6iOOHNqUMTpAsxDijuXeaAlSZHkh42mJfs



projectUrl:
  wechatMpAuthorize: http://7dian.nat300.top
 # wechatOpenAuthorize: http://7dian.nat300.top
  wechatOpenAuthorize: http://sell.springboot.cn
  sell: http://7dian.nat300.top